# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7114697cd7fd6166049aee534399214378019599c9998d2efd6df7da0a694d4224a91e856aa6e0e1221f4665681cdcb4288cea89f8be98341fc506193086255e

test:
  secret_key_base: 447c1a90728c0a5455eb9e8e3653b5b36c2f015542c9ec3ffcf22fa6e65c9b2b8d2d7e9ff38ecdce74fd71397b1dcbce8139e842acb441913a4dae4db634bfee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
